qa327/views/buy.py
from flask import Blueprint, redirect,  request, render_template, make_response, session
import qa327.library.tickets as tic
import qa327.library.validation as valid
import qa327.library.users as usr

'''
The following functions allow the user to fill out ticket name and quantity
when buying a ticket. If the ticket fails to post, users are given an error
message and redirected to the homepage
'''

buy_page = Blueprint('buy_page', __name__)

@buy_page.route('/', methods=['GET'])
def buy_get():
    return redirect('/', code=303)

@buy_page.route('/', methods=['POST'])
def buy_post():
    ticket_name = request.form.get('ticket_name')   # Set ticket name from form
    email=session['logged_in']                      # Set email from logged in session
    quantity = request.form.get('quantity')         # Set quanity from from
    errors=[]                                       # Create an empty arry to store errors
    buy_msg = 'Failed to buy the ticket(s): '       # Set buy_msg to a failed message

    user = usr.get_user(email)
    balance = user.balance/100
    
    # Check that the ticket name meets requirements
    if not valid.validate_name(ticket_name):
        errors.append("The name of the ticket must be no more than 60 characters using alphanumeric characters with no spaces at the begining and end")
    # Check that the quantity is valid
    if not quantity.isdigit():
         errors.append("Quantity must be entered using 0-9")   
    elif not valid.validate_quantity(quantity) or int (quantity)==0:
         errors.append("You may only buy between 0 and 100 tickets inclusive")   

    # If no errors in input
    if len(errors) == 0:

        # Try to buy the ticket
        ticket = tic.buy_ticket(ticket_name, quantity, balance, email)

        # If successfully bought change buy msg to show that
        if ticket is None:
            buy_msg = 'Successfully bought the ticket(s).'

        # If failed add to errors
        else:
            errors.append(ticket)
            buy_msg = buy_msg + str(ticket)

    # If there are errors in input create message
    elif len(errors) > 0:
        buy_msg += ", ".join(errors)+"." #adding all of the errors to the update message

    resp=make_response(redirect('/', code=303)) 
    resp.set_cookie('buy_msg', buy_msg)
    return resp

qa327/views/login.py
from flask import Blueprint, render_template, request, session, redirect
import qa327.library.users as usr
import qa327.library.validation as valid

"""
This file defines the login page through blueprint, and implements the necessary front
end input processing to log a user in.
"""

login_page = Blueprint('login_page', __name__, template_folder='templates')

@login_page.route('/', methods=['GET'])
def login_get():
    """
    Displays the login page at the "/login" route
    """
    if 'logged_in' in session:
        return redirect('/', code=303)
    else:
        return render_template('login.html', message='Please login')


@login_page.route('/', methods=['POST'])
def login_post():
    """
    Collects field data from the login screen and calls the requisite backend login functions
    to validate the user or reject their credentials.
    """
    email = request.form.get('email')
    password = request.form.get('password')
    if not valid.validate_email_address(email) or not valid.validate_password(password):
        return render_template('login.html', message='email/password format is incorrect.')

    user = usr.login_user(email, password)
    if user:
        session['logged_in'] = user.email
        """
        Session is an object that contains sharing information 
        between browser and the end server. Typically it is encrypted 
        and stored in the browser cookies. They will be past 
        along between every request the browser made to this services.

        Here we store the user object into the session, so we can tell
        if the client has already login in the following sessions.
        """
        # success! go back to the home page
        # code 303 is to force a 'GET' request
        return redirect('/', code=303)
    else:
        return render_template('login.html', message='email/password combination incorrect')

qa327/views/register.py
from flask import Blueprint, render_template, request, session, redirect
import qa327.library.users as usr
import qa327.library.validation as valid

"""
This file defines the registration routes, displays a registration page, and performs all of the front end
data collection logic to call the backend registration functions.
"""

register_page = Blueprint('register_page', __name__, template_folder='templates')

@register_page.route('/', methods=['GET'])
def register_get():
    """
    If a user is logged in redirect to the home page.
    Otherwise displays a registration page.
    """
    if 'logged_in' in session:
        return redirect('/', code=303)
    else:
        # templates are stored in the templates folder
        return render_template('register.html', message='Please Register')


@register_page.route('/', methods=['POST'])
def register_post():
    """
    This function collects all of the necessary field data,
    validates the entered data to some standard, then uses
    the backend registration calls to save the new user to
    our database or requests valid data.
    """
    # All of the inforamtion used to register a user gotten from the form
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')
    password2 = request.form.get('password2')
    error_message = None

    # The users name with out spaces, to be used for validation
    nameNoSpace = name.replace(" ", "")

    '''
    A series of conditionals checking if the user's registration input is
    valid or not.
    If it is not an accurate error message will be displayed.
    If it is valid the user will be registered and redirected to the login page.
    '''

    # Check if passwords match
    if password != password2:
        error_message = "Passwords format is incorrect"
    # Check for valid email
    elif not valid.validate_email_address(email):
        error_message = "Email format is incorrect"
    # Check for valid password
    elif not valid.validate_password(password):
        error_message = "Password format is incorrect"
    # Check that the length of the name is proper length
    elif len(name) > 19 or len(name)<3:
        error_message = "Username format is incorrect"
    # Check that there are no non alphanumeric characters other then space
    elif not nameNoSpace.isalnum():
        error_message = "Username format is incorrect"
    # Check that there is no space at begining or end
    elif name[0] == ' ' or name[len(name) - 1] == ' ':
        error_message = "Username format is incorrect"
    else:
        user = usr.get_user(email)
        # Check if email has already been used
        if user:
            error_message = "This email has ALREADY been used"
        # Register User
        elif usr.register_user(email, name, password, password2, 500000):
            error_message = "Failed to store user info."

    # if there is any error messages when registering new user
    # at the backend, go back to the register page.
    if error_message:
        return render_template('register.html', message=error_message)
    else:
        return redirect('/login')

qa327/views/sell.py
from flask import Blueprint, redirect, session, request, make_response
import qa327.library.validation as valid
import qa327.library.tickets as tic

'''
The following functions allow the user to fill out ticket name, quantity,
price and expiration date for the ticket they want to post to sell. If
the ticket fails to post, users are given an error message and redirected
to the homepage
'''

sell_page = Blueprint('sell_page', __name__)

# if someone is trying to GET this route, redirect them back to the homepage.
@sell_page.route('/', methods=['GET'])
def sell_get():
    return redirect('/', code=303)


@sell_page.route('/', methods=['POST'])
def sell_post():
	"""
	When someone tries to post a ticket listing to this route,
	validate the details, and if validation is successful
	attempt to list the ticket; may fail if ticket has already been posted by user.
	"""
	email = session['logged_in']
	ticket_name = request.form.get('ticket_name')
	quantity = request.form.get('quantity')
	price = request.form.get('price')
	expiration = request.form.get('expiration')
	errors = []
	sell_msg='Failed to list the ticket(s): '

	if not valid.validate_name(ticket_name):
		errors.append("The name of the ticket names must be longer than 6-characters, shorter than 60 characters, and be alpha-numeric with spaces (spaces are not allowed at the beginning or the end)")
	if not valid.validate_quantity(quantity):
		errors.append("You may only sell between 1 and 100 tickets at a time with SeetGeek")
	if not valid.validate_price(price):
		errors.append("Prices must be between $10 and $100 (whole numbers only)")
	if not valid.validate_not_expired(expiration):
		errors.append("Ticket cannot be expired and must conform to YYYYMMDD format")
	if len(errors) == 0:
		ticket = tic.add_ticket(ticket_name, quantity, price, expiration, email)
		if ticket is None:
			sell_msg='Successfully listed the ticket(s)'
		else:
			errors.append(ticket)

	#merge the errors together.
	if len(errors) > 0:
		sell_msg += ", ".join(errors)+"."
	
	resp = make_response(redirect('/', code=303))
	resp.set_cookie('sell_msg', sell_msg)
	return resp

qa327/views/update.py
from flask import Blueprint, redirect, session, request, make_response
import qa327.library.validation as valid
import qa327.library.tickets as tic

'''
The following functions allow the user to fill out ticket name, quantity,
price and expiration date in order to update a ticket.
If the ticket fails to post, users are given an error message and redirected
to the homepage
'''

update_page = Blueprint('update_page', __name__)

@update_page.route('/', methods=['GET'])
def update_get():
    return redirect('/', code=303)

@update_page.route('/', methods=['POST'])
def update_post():
    ticket_name = request.form.get('ticket_name')
    email=session['logged_in']
    quantity = request.form.get('quantity')
    price = request.form.get('price')
    expiration = request.form.get('expiration')
    errors=[]
    update_msg='Failed to update the ticket(s): '
    
    if not valid.validate_name(ticket_name):
        errors.append("The name of the ticket cannot be: blank, contain more than 60 characters, contain soecial characters, or any white space")
    #if not valid.validate_quantity(quantity) and int(quantity)!=0:
    #errors.append("You may only sell between 0 and a hundred tickets inclusive")

    if not valid.validate_quantity(quantity):
        errors.append("You may only sell between one and a hundred tickets inclusive, and quantity listed must be in numeric form")

    if not valid.validate_price(price):
        errors.append("Prices must be between $10 and $100 (whole numbers only)")
    if not valid.validate_date(expiration):
    	errors.append("Date must be in the format YYYYMMDD, no separators and cannot be blank")

    if len(errors) == 0:
        ticket = tic.update_ticket(ticket_name, quantity, price, expiration, email)

        if ticket is None:
            update_msg = 'Successfully updated the ticket(s)'
        else:
            errors.append(ticket)
    if len(errors) > 0:
       update_msg += ", ".join(errors)+"." #adding all of the errors to the updat message

    resp=make_response(redirect('/', code=303))
    resp.set_cookie('update_msg', update_msg)
    return resp

qa327/templates/index.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Profile{% endblock %}</h1>
{% endblock %}

{% block content %}
<h2 id="welcome-header">Hi {{ user.name }}</h2>

<h3 id="user-balance">Your balance is {{ balance }}</h3>


<h2 id="available-tickets">Here are all available tickets</h2>

<div id="tickets">
{% for ticket in tickets %}
    <div>
        <h4 class="ticket-info"><span id='ticket{{ loop.index }}_quantity'>(x{{ ticket.quantity }})</span> <span id='ticket{{ loop.index }}_name'>{{ ticket.ticket_name }}</span> <span id='ticket{{ loop.index }}_price'>${{ ticket.price }}</span> Sold By: <span id='ticket{{ loop.index }}_owner'>{{ ticket.owners_email }}</span></h4>
    </div>
{% endfor %}
</div>

<ul> 
	<li>
		<h1 id="buy-ticket">Buy Ticket</h1>
		<span id='buy_message'>{{ buy_msg }}</span>
		<form method='POST' action="{{ url_for('buy_page.buy_post') }}">
 
			<label for='ticket_name'> Name: </label>

			<input type='text' name='ticket_name' id='buy-ticket-name' required/> 
	
			<label for='quantity'> Quantity: </label>
			<input type='text' name='quantity' id='buy-quantity' required/> 
 
			<input type='submit' id='buy-submit'/>

		</form>
	</li>
    <h4 id='buy_message'>{{buy_message}}</h4>
	
	
	<li> 
		<h1 id="sell-ticket">Sell Ticket</h1>
		<span id='sell_message'>{{ sell_msg }}</span>
		<form method='POST' action="{{ url_for('sell_page.sell_post') }}">
 
			<label for='ticket_name'> Name: </label>

			<input type='text' name='ticket_name' id='sell-ticket-name' requiered/> 
	
			<label for='quantity'> Quantity: </label>
			<input type='text' name='quantity' id='sell-quantity' required/> 
	
			<label for='price'> Price: </label>
			<input type='text' name='price' id='sell-price' required/> 
	
			<label for='expiration'> Expiration Date: </label>
			<input type='text' name='expiration' id='sell-expiration' required/> 
	
			<input type='submit' id='sell-submit'/> 

		</form>
		<h4 id='sell_message'>{{ sell_message }}</h4>
	</li>
    <h5 id='sell_message'>{{sell_message}}</h5>
	
	
	<li> 
		<h1 id="update-ticket">Update Ticket</h1>
		<span id='update_message'>{{ update_msg }}</span>
		<form method='POST' action="{{ url_for('update_page.update_post') }}">
 
			<label for='ticket_name'> Name: </label>

			<input type='text' name='ticket_name' id='update-ticket-name' required/> 
	
			<label for='quantity'> Quantity: </label>
			<input type='text' name='quantity' id='update-quantity' required/> 
	
			<label for='price'> Price: </label>
			<input type='text' name='price' id='update-price' required/> 
	
			<label for='expiration'> Expiration Date: </label>
			<input type='text' name='expiration' id='update-expiration' required/> 
	
			<input type='submit' id='update-submit'/> 
		</form>
	</li>
     <h6 id='update_message'>{{update_message}}</h6>
</ul>


<a href='/logout' id="logout">logout</a>

{% endblock %}

qa327/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1 id='log-in-header'>{% block title %}Log In{% endblock %}</h1>
<h4 id='message'>{{message}}</h4>
<form method="post">
  <div class="form-group">
    <label for="email">Email</label>
    <input class="form-control" name="email" id="email" required>
    <label for="password">Password</label>
    <input class="form-control" type="password" name="password" id="password" required>
    <input class="btn btn-lg btn-primary" type="submit" id="btn-submit" value="Log In">
  </div>
</form>
<a href='/register'>Register</a>
{% endblock %}

qa327/templates/register.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
<h4 id='message'>{{message}}</h4>
<form method="post">
  <div class="form-group">
    <label for="email">Email</label>
    <input class="form-control" name="email" id="email" required>
    <label for="name">Name</label>
    <input class="form-control" name="name" id="name" required>
    <label for="password">Password</label>
    <input class="form-control" type="password" name="password" id="password" required>
    <label for="password">Confirm Password</label>
    <input class="form-control" type="password" name="password2" id="password2" required>
    <input class="btn btn-primary" type="submit" value="Register">
  <a href='/login' class="btn btn-primary" id="btn-submit" >Login</a>
  </div>
</form>
{% endblock %}